[build]
  command = "CI=false npm run build"
  publish = "build"

# Set environment variables
[build.environment]
  CI = "false"

# Handle SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 